version: '3'

services:
  tizori-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tizori-api
    ports:
      - 80:3000
    volumes:
      - ./:/user/src/app
    env_file:
      - ./.env/.local
    depends_on:
      - postgres
    networks:
      - tizori-network

  postgres:
    image: postgres
    container_name: tizori-postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - ./.env/.local
    ports:
      - 5432:5432
    networks:
      - tizori-network
      
volumes:
  postgres-db:

networks:
  tizori-network: