version: '3'

services:
  tizori-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tizori-api
    ports:
      - 3000:3000
    volumes:
      - ./:/user/src/app
    env_file:
      - ./.env/.local
    depends_on:
      - postgres
    networks:
      - tizori-network
    restart: always

  postgres:
    image: postgres
    container_name: tizori-postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - ./.env/.local
    ports:
      - 5432:5432
    networks:
      - tizori-network
  
  # Generating SSL certificates using traefik
  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    container_name: tizori-traefik
    depends_on:
      - tizori-api
    volumes:
      - traefik-volume:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
    networks:
      - tizori-network

volumes:
  postgres-db:
  traefik-volume:

networks:
  tizori-network: