log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "dhruvshahrds@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`tizori-api.dscvit.com`)"
      entryPoints:
        - web-secure
      service: tizori-api
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    admin-secure-router:
      rule: "Host(`tizori-admin.dscvit.com`)"  # Change the host rule as needed
      entryPoints:
        - web-secure
      service: tizori-admin
      tls:
        certResolver: letsencrypt
  
  services:
    tizori-api:
      loadBalancer:
        servers:
          - url: http://tizori-api:3000

    tizori-admin:
      loadBalancer:
        servers:
          - url: http://tizori-admin:8080

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true